COUNTRY_CODES = [
    {"country_name": "United+States", "country_code": "US"},
    {"country_name": "United+Kingdom", "country_code": "GB"},
    {"country_name": "Canada", "country_code": "CA"},
    {"country_name": "Australia", "country_code": "AU"},
    {"country_name": "New Zealand", "country_code": "NZ"},
    {"country_name": "Japan", "country_code": "JP"},
    {"country_name": "Germany", "country_code": "DE"},
    {"country_name": "France", "country_code": "FR"},
    {"country_name": "Netherlands", "country_code": "NL"},
    {"country_name": "Italy", "country_code": "IT"},
    {"country_name": "Spain", "country_code": "ES"},
    {"country_name": "Sweden", "country_code": "SE"},
    {"country_name": "Denmark", "country_code": "DK"},
    {"country_name": "Norway", "country_code": "NO"},
    {"country_name": "Finland", "country_code": "FI"},
    {"country_name": "Switzerland", "country_code": "CH"},
    {"country_name": "Belgium", "country_code": "BE"},
    {"country_name": "Austria", "country_code": "AT"},
    {"country_name": "Ireland", "country_code": "IE"},
    {"country_name": "Poland", "country_code": "PL"},
    {"country_name": "Taiwan", "country_code": "TW"},
]

YEARS = [
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "2024",
]

US_STATES = [
    {"institution_state_codes": "US-AL", "state_query": "Alabama"},
    {"institution_state_codes": "US-AK", "state_query": "Alaska"},
    {"institution_state_codes": "US-AZ", "state_query": "Arizona"},
    {"institution_state_codes": "US-AR", "state_query": "Arkansas"},
    {"institution_state_codes": "US-CA", "state_query": "California"},
    {"institution_state_codes": "US-CO", "state_query": "Colorado"},
    {"institution_state_codes": "US-CT", "state_query": "Connecticut"},
    {"institution_state_codes": "US-DE", "state_query": "Delaware"},
    {"institution_state_codes": "US-FL", "state_query": "Florida"},
    {"institution_state_codes": "US-GA", "state_query": "Georgia"},
    {"institution_state_codes": "US-HI", "state_query": "Hawaii"},
    {"institution_state_codes": "US-ID", "state_query": "Idaho"},
    {"institution_state_codes": "US-IL", "state_query": "Illinois"},
    {"institution_state_codes": "US-IN", "state_query": "Indiana"},
    {"institution_state_codes": "US-IA", "state_query": "Iowa"},
    {"institution_state_codes": "US-KS", "state_query": "Kansas"},
    {"institution_state_codes": "US-KY", "state_query": "Kentucky"},
    {"institution_state_codes": "US-LA", "state_query": "Louisiana"},
    {"institution_state_codes": "US-ME", "state_query": "Maine"},
    {"institution_state_codes": "US-MD", "state_query": "Maryland"},
    {"institution_state_codes": "US-MA", "state_query": "Massachusetts"},
    {"institution_state_codes": "US-MI", "state_query": "Michigan"},
    {"institution_state_codes": "US-MN", "state_query": "Minnesota"},
    {"institution_state_codes": "US-MS", "state_query": "Mississippi"},
    {"institution_state_codes": "US-MO", "state_query": "Missouri"},
    {"institution_state_codes": "US-MT", "state_query": "Montana"},
    {"institution_state_codes": "US-NE", "state_query": "Nebraska"},
    {"institution_state_codes": "US-NV", "state_query": "Nevada"},
    {"institution_state_codes": "US-NH", "state_query": "New Hampshire"},
    {"institution_state_codes": "US-NJ", "state_query": "New Jersey"},
    {"institution_state_codes": "US-NM", "state_query": "New Mexico"},
    {"institution_state_codes": "US-NY", "state_query": "New York"},
    {"institution_state_codes": "US-NC", "state_query": "North Carolina"},
    {"institution_state_codes": "US-ND", "state_query": "North Dakota"},
    {"institution_state_codes": "US-OH", "state_query": "Ohio"},
    {"institution_state_codes": "US-OK", "state_query": "Oklahoma"},
    {"institution_state_codes": "US-OR", "state_query": "Oregon"},
    {"institution_state_codes": "US-PA", "state_query": "Pennsylvania"},
    {"institution_state_codes": "US-RI", "state_query": "Rhode Island"},
    {"institution_state_codes": "US-SC", "state_query": "South Carolina"},
    {"institution_state_codes": "US-SD", "state_query": "South Dakota"},
    {"institution_state_codes": "US-TN", "state_query": "Tennessee"},
    {"institution_state_codes": "US-TX", "state_query": "Texas"},
    {"institution_state_codes": "US-UT", "state_query": "Utah"},
    {"institution_state_codes": "US-VT", "state_query": "Vermont"},
    {"institution_state_codes": "US-VA", "state_query": "Virginia"},
    {"institution_state_codes": "US-WA", "state_query": "Washington"},
    {"institution_state_codes": "US-WV", "state_query": "West Virginia"},
    {"institution_state_codes": "US-WI", "state_query": "Wisconsin"},
    {"institution_state_codes": "US-WY", "state_query": "Wyoming"},
]

EXPERIMENTAL_KEYWORDS = [
    "NMR",
    "X-ray",
    "cryo-EM",
    "crystallography",
    "cryoelectron microscopy",
]

EXPERIMENTAL_LOOSE_KEYWORDS = [
    "experimental"
]

COMPUTATIONAL_KEYWORDS = [
    "computational",
    "modeling",
    "simulation",
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "AI",
    "neural network",
    "bioinformatics",
    "structural bioinformatics",
]

STRUCTURAL_BIOLOGY_KEYWORDS = [
    "structural biology",
    "structural bioinformatics",
    "protein structure",
    "protein structure prediction",
    "protein structure modeling",
    "protein structure determination",
    "protein structure analysis",
    "protein structure comparison",
    "protein structure alignment",
    "protein structure visualization",
    "protein structure classification",
    "molecular dynamics",
    "molecular modeling",
    "protein design",
    "protein engineering",
    "protein folding",
    "protein structure prediction",
    "protein structure",
    "protein function",
    "protein-ligand",
    "protein-protein",
    "protein-RNA",
    "protein-DNA",
    "protein-small molecule",
    "protein-peptide",
    "protein-protein interaction",
    "protein-RNA interaction",
    "protein-DNA interaction",
    "protein-small molecule interaction",
    "protein-peptide interaction",
    "protein-protein docking",
    "protein-RNA docking",
    "protein-DNA docking",
    "protein-small molecule docking",
    "protein-peptide docking",
    "protein-protein interaction prediction",
    "protein-RNA interaction prediction",
    "protein-DNA interaction prediction",
    "protein-small molecule interaction prediction",
    "protein-peptide interaction prediction",
    "protein-protein docking prediction",
    "protein-RNA docking prediction",
    "protein-DNA docking prediction",
    "protein-small molecule docking prediction",
    "protein-peptide docking prediction",
    "protein-protein interaction modeling",
    "protein-RNA interaction modeling",
    "protein-DNA interaction modeling",
    "protein-small molecule interaction modeling",
    "protein-peptide interaction modeling",
    "protein-protein docking modeling",
    "protein-RNA docking modeling",
    "protein-DNA docking modeling",

]