# OpenAlex (oa) configuration
oa:
  data_collection:
    # API configuration
    api: &api
      mailto: data_analytics@nesta.org.uk
      perpage: "200"
  
    # Data retrieval settings
    get: &get
      work_id: W3177828909
      work_ids: 
        - W3177828909
        - W3211795435
        - W3202105508


    # Retrieval directions
    direction:
      cited_by:
        get: *get
        api: *api
        filter: cited_by
      cites:
        get: *get
        api: *api
        filter: cites

    # Downstream works
    downstream:
      api: *api
      get: *get
      filter: cites

    # Citation depth works
    depth:
      api: *api
      get: *get
      filter: cites
      max_depth: 3
      levels:
        0: 0
        1: 1
        2: 2
        3: 3

    
    # Works for concepts
    works_for_concepts:
      test_concept_ids:
        - "c10010492" # Protein sequencing
        - "c204328495" # Protein folding
      test_publication_years:
        - 2022
        - 2023

    subfield:
      structural_biology:
        concept_ids: &sb_concept_ids
          - c191120209 # Structural biology
          - c69131567 # Structural bioinformatics
          - c200307862 # Threading (protein sequence)
          - c75599170 # Protein tertiary structure
          - c104292427 # Protein subunit
          - c18051474 # Protein structure prediction
          - c136475424 # Protein structure database
          - c47701112 # Protein structure
          - c10010492 # Protein sequencing
          - c62614982 # Protein secondary structure
          - c109095088 # Protein ligand
          - c207060522 # Protein function prediction
          - c2986374874 # Protein function
          - c204328495 # Protein folding
          - c119145174 # Protein data bank
          - c2778815515 # Intrinsically disordered proteins
        from_date: "2010-01-01"
        api: *api
      biochemistry:
        concept_ids: &bc_concept_ids
          - c55493867 # Biochemistry
          - c12554922 # Biophysics
          - c71240020 # Stereochmistry
        from_date: "2010-01-01"
        api: *api
      bioinformatics:
        concept_ids: &bi_concept_ids
          - c70721500 # Computational biology
          - c60644358 # Bioinformatics
        from_date: "2010-01-01"
        api: *api
      drug_discovery:
        concept_ids: &dd_concept_ids
          - c74187038 # Drug discovery
          - c98274493 # Pharmacology
          - c64903051 # Drug development
          - c103637391 # Drug repositioning
          - c150903083 # Biotechnology
          - c163763905 # Precision medicine
        from_date: "2010-01-01"
        api: *api
      molecular_biology:
        concept_ids: &mb_concept_ids
          - c95444343 # Cell biology
          - c159047783 # Virology
          - c89423630 # Microbiology
          - c153911025 # Molecular biology
        from_date: "2010-01-01"
        api: *api
      protein_design:
        concept_ids:  &pd_concept_ids
          - c191908910 # Synthetic biology
          - c53105671 # Rational design
          - c147816474 # Protein engineering
          - c152769699 # Protein design
          - c3675279 # Protein biosynthesis
        from_date: "2010-01-01"
        api: *api
      systems_biology:
        concept_ids:  &sysb_concept_ids
          - c46111723 # Proteomics
          - c152662350 # Systems biology
          - c21565614 # Metabolomics
        from_date: "2010-01-01"
        api: *api
      artificial_intelligence:
        concept_ids: &ai_concept_ids
          - c154945302 # Artificial intelligence
          - c119857082 # Machine learning
          - c2522767166 # Data science
          - c108583219 # Deep learning
          - c50644808 # Artificial neural network
          - c124101348 # Data mining
        from_date: "2010-01-01"
        api: *api
        and_ids:
          - *sb_concept_ids
          - *bc_concept_ids
          - *bi_concept_ids
          - *dd_concept_ids
          - *mb_concept_ids
          - *pd_concept_ids
          - *sysb_concept_ids
          
    # Additional settings
    config: &config
      subfolder: work_id
      group_work_ids: True
      eager_loading: True
      slice_keys: True
      parallelise: True

    # Filtering options
    gtr:
      api: *api
      config: *config
      filter_doi: doi
      filter_oa: "ids.openalex"

  data_processing:
    depth:
      seed_id: W3177828909
      mesh_tagging:
        id_col: child_id
        text_col: abstract
        batch_name: funding_opps
        cmd: MTI
        cmdargs: -MoD_PP

test_concept_ids:
  - "c10010492" # Protein sequencing
  - "c204328495" # Protein folding

test_publication_years:
  - 2022
  - 2023

# Gateway to Research (gtr) configuration
gtr:
  # Data collection parameters
  data_collection:

    # Common request parameters
    _param_requests:
      gtr_config:
        base_url: https://gtr.ukri.org/gtr/api/
        headers:
          Accept: application/vnd.rcuk.gtr.json-v7
        page_size: 100
      max_retries: 5
      backoff_factor: 0.3

    # Specific data endpoints
    outcomes/publications:
      param_requests: ${.._param_requests}
      label: outcomes/publications
    organisations:
      param_requests: ${.._param_requests}
      label: organisations
    funds:
      param_requests: ${.._param_requests}
      label: funds
    projects:
      param_requests: ${.._param_requests}
      label: projects

# National Institutes of Health (nih) configuration 
nih:
  # Data collection parameters
  data_collection:
    clinical_trials:
      download_url: https://classic.clinicaltrials.gov/AllAPIJSON.zip
      zip_save_path: data/00_tmp/nih_ct.zip
      extract_path: data/01_raw/nih/clinical_trials/
    funded_projects:
      api_url: 'https://api.reporter.nih.gov/v2/projects/search'
      years:
        - 2018
        - 2019
        - 2020 
        - 2021
        - 2022
        - 2023
        - 2024
    funding_opportunities:
      api_url: 'https://search.grants.nih.gov/guide/api/data'
      end_date: '10022024'
  data_processing:
    funding_opportunities:
      year: 2017
      mesh_tagging:
        id_col: id
        text_col: purpose
        batch_name: funding_opps
        cmd: MTI
        cmdargs: -MoD_PP
  data_analysis:
    funding_opportunities:
      mesh_tree_structural_bio:
        "Protein Conformation":
          - "G02.111.570.820.709"
        "Databases, Protein":
          - "L01.313.500.750.300.188.400.300.750"
          - "L01.313.500.750.300.188.400.325.710"
          - "L01.470.750.750.300.750"
          - "L01.470.750.750.325.710"
        "Protein Folding":
          - "G01.154.651"
          - "G02.111.688"
        "Models, Molecular":
          - "E05.599.595"
        "Molecular Docking Simulation":
          - "E05.599.595.249"
          - "L01.224.160.249"
        "Protein Structure, Secondary":
          - "G02.111.570.820.709.600"
        "Protein Structure, Tertiary":
          - "G02.111.570.820.709.610"
        "Protein Structure, Quaternary":
          - "G02.111.570.820.709.550"
        "Protein Subunits":
          - "D12.776.813"
        "Protein Strucutal Elements":
          - "G02.111.570.820.709.275"
        "Protein Multimerization":
          - "G02.111.694"
        "Protein Engineering":
          - "E05.393.420.601"
      mesh_tree_experimental_bio:
        "Crystallography, X-Ray":
          - "E05.196.309.742.225"
        "Cryoelectron Microscopy":
          - "E05.595.402.150"
          - "E01.370.350.515.402.150"
        "Nuclear Magnetic Resonance, Biomolecular":
          - "E05.196.867.519.550"
      search_terms_structural_bio:
        - "protein folding"
        - "structural biology"
        - "structural bioinformatics"
        - "protein structure"
        - "protein structure prediction"
        - "protein tertiary structure"
        - "protein subunit"
        - "protein structure database"
        - "protein sequencing"
        - "protein secondary structure"
        - "protein ligand"
        - "protein function prediction"
        - "protein function"
        - "protein data bank"
        - "intrinsically disordered proteins"
        - "protein multimerization"
        - "protein engineering"
        - "protein conformation"
        - "molecular models"
        - "molecular docking simulation"
      search_terms_experimental_bio:
        - "x-ray crystallography"
        - "xray crystallography"
        - "cryoelectron microscopy"
        - "cryoem"
        - "cryo-em"
        - "biomolecular nuclear magnetic resonance"
        - "nuclear magnetic resonance"
      search_cols:
        - "title"
        - "purpose"
        - "doctext"
      subfield_label_structural_bio: "Structural Biology"
      subfield_label_experimental_bio: "Experimental Biology"

mesh_tagging:
  # email: ${oc.env:UMLS_EMAIL}
  # api_key: ${oc.env:UMLS_API_KEY}

lens:
  data_collection:
    api:
      base_url: 'https://api.lens.org/patent/search'
      token: QrN2bSOp8NiVSktDd8gWZ8Y5XMDsejM8hnID6dgUr1F80nSHvBfU # ${..lens_token}
      size: 100
      max_retries: 5
      backoff_factor: 0.3
    jurisdictions:
      united_states: US
      european_union: EP
    months:
      "01": "01"
      "02": "02"
      "03": "03"
      "04": "04"
      "05": "05"
      "06": "06"
      "07": "07"
      "08": "08"
      "09": "09"
      "10": "10"
      "11": "11"
      "12": "12"
    years:
      "2021": "2021"
      "2022": "2022"
      "2023": "2023"
      "2024": "2024"

s2:
  data_collection:
    strength:
      af_paper: W3177828909
      af_doi: 10.1038/s41586-021-03819-2
      api:
        key: 0lnUkuBhBJ8NUT2RxpK9j82yWGfUL2I81UmlwN6b
        base_url: https://api.semanticscholar.org/graph/v1/paper
        cites: citations
        cited_by: references
        fields:
          - externalIds
          - contextsWithIntent
          - isInfluential
        perpage: 500
      min_level: 0
      max_level: 5

nsf:
  data_collection:
    api:
      base_url: http://api.nsf.gov/services/v1/awards.json
      max_retries: 5
      backoff_factor: 0.3
    variables:
      - parentUeiNumber
      - ueiNumber
      - title
      - abstractText
      - awardee
      - pdPIName
      - coPDPI
      - date
      - startDate
      - expDate
      - estimatedTotalAmt
      - fundsObligatedAmt
      - fundProgramName
      - awardeeCity
      - awardeeCountryCode
      - awardeeDistrictCode
      - awardeeStateCode
      - awardeeZipCode
      - perfCity
      - perfCountryCode
      - perfDistrictCode
      - perfLocation
      - perfStateCode
      - perfZipCode
      - poName
      - primaryProgram
      - transType
      - cfdaNumber
      - agency
      - fundAgencyCode
      - awardAgencyCode
      - publicationResearch
      - publicationConference
      - projectOutComesReport
      - id
    archived_funding_opportunities:
      base_url: https://www.nsf.gov
      archived_search_url: https://www.nsf.gov/funding/archived_funding_results.jsp?queryText=&date_slct=0&pubStatus=ARCHIVED&fundingType=0&nsfOrgs=allorg&advForm=true&Submit=&showItems=1000
      api:
        max_retries: 5
        backoff_factor: 0.3
      
labs:
  data_collection:
    filter:
      0: False
      1: False
      2: False
      3: False
      structural_biology: True
      protein_design: True
      biochemistry: True
      bioinformatics: True
    from_date: "2015-01-01"
    from_author_date: "2018-01-01"
    api:
      mailto: data_analytics@nesta.org.uk
      perpage: "200"

sb_labs:
  data_collection:
    depth:
      ct_start_level: 2
      max_depth: 3

tcc:
  "af_label": "Papers that cite AF levels 0-3"
  "biochemistry_label": "Biochemistry"
  "bioinformatics_label": "Bioinformatics"
  "protein_design_label": "Protein Design"
  "structural_biology_label": "Structural Biology"
  partition_order:
    - "Papers that cite AF levels 0-3"
    - "Biochemistry"
    - "Bioinformatics"
    - "Protein Design"
    - "Structural Biology"

test: False

true_: True
false_: False

chains:
  identifier:
    id: "id"
    pmid: "pmid"
    doi: "doi"
  num_levels:
    af: 3
    ct: 3
    other: 2
  
pdb:
  config:
    max_retries: 5
    backoff_factor: 0.3

start_level: 1
max_level: 3

analysis:
  source:
    af: "af"
    ct: "ct"
    other: "other"
  output_type:
    publications: "publications"
    citations: "citations"