# OpenAlex (oa) configuration
oa:
  data_collection:
    # API configuration
    api: &api
      mailto: data_analytics@nesta.org.uk
      perpage: "200"
  
    # Data retrieval settings
    get: &get
      work_id: W3177828909 # AlphaFold

    # Retrieval directions
    direction:
      cited_by:
        get: *get
        api: *api
        filter: cited_by
      cites:
        get: *get
        api: *api
        filter: cites

    # Downstream works
    downstream:
      api: *api
      get: *get
      filter: cites

    # Citation depth works
    depth:
      api: *api
      get: *get
      filter: cites

    # Additional settings
    config: &config
      subfolder: work_id
      group_work_ids: True
      eager_loading: True
      slice_keys: True
      parallelise: True

    # Filtering options
    gtr:
      api: *api
      config: *config
      filter_doi: doi
      filter_oa: "ids.openalex"

test_concept_ids:
  - "c10010492" # Protein sequencing
  - "c204328495" # Protein folding

test_publication_years:
  - 2022
  - 2023

# Gateway to Research (gtr) configuration
gtr:
  # Data collection parameters
  data_collection:

    # Common request parameters
    _param_requests:
      gtr_config:
        base_url: https://gtr.ukri.org/gtr/api/
        headers:
          Accept: application/vnd.rcuk.gtr.json-v7
        page_size: 100
      max_retries: 5
      backoff_factor: 0.3

    # Specific data endpoints
    outcomes/publications:
      param_requests: ${.._param_requests}
      label: outcomes/publications
    organisations:
      param_requests: ${.._param_requests}
      label: organisations
    funds:
      param_requests: ${.._param_requests}
      label: funds
    projects:
      param_requests: ${.._param_requests}
      label: projects

# National Institutes of Health (nih) configuration 
nih:
  # Data collection parameters
  data_collection:
    clinical_trials:
      download_url: https://classic.clinicaltrials.gov/AllAPIJSON.zip
      zip_save_path: data/00_tmp/nih_ct.zip
      extract_path: data/01_raw/nih/clinical_trials/
    funded_projects:
      api_url: 'https://api.reporter.nih.gov/v2/projects/search'
      years:
        - 2018
        - 2019
        - 2020 
        - 2021
        - 2022
        - 2023
        - 2024
    funding_opportunities:
      api_url: 'https://search.grants.nih.gov/guide/api/data'
      end_date: '10022024'
  data_processing:
    funding_opportunities:
      year: 2017

lens:
  data_collection:
    api:
      base_url: 'https://api.lens.org/patent/search'
      token: QrN2bSOp8NiVSktDd8gWZ8Y5XMDsejM8hnID6dgUr1F80nSHvBfU # ${..lens_token}
      size: 100
      max_retries: 5
      backoff_factor: 0.3
    jurisdictions:
      united_states: US
      european_union: EP
    months:
      "01": "01"
      "02": "02"
      "03": "03"
      "04": "04"
      "05": "05"
      "06": "06"
      "07": "07"
      "08": "08"
      "09": "09"
      "10": "10"
      "11": "11"
      "12": "12"
    years:
      "2021": "2021"
      "2022": "2022"
      "2023": "2023"
      "2024": "2024"


nsf:
  data_collection:
    api:
      base_url: http://api.nsf.gov/services/v1/awards.json
      max_retries: 5
      backoff_factor: 0.3
    variables:
      - parentUeiNumber
      - ueiNumber
      - title
      - abstractText
      - awardee
      - pdPIName
      - coPDPI
      - date
      - startDate
      - expDate
      - estimatedTotalAmt
      - fundsObligatedAmt
      - fundProgramName
      - awardeeCity
      - awardeeCountryCode
      - awardeeDistrictCode
      - awardeeStateCode
      - awardeeZipCode
      - perfCity
      - perfCountryCode
      - perfDistrictCode
      - perfLocation
      - perfStateCode
      - perfZipCode
      - poName
      - primaryProgram
      - transType
      - cfdaNumber
      - agency
      - fundAgencyCode
      - awardAgencyCode
      - publicationResearch
      - publicationConference
      - projectOutComesReport
      - id
      
test: False